export const GET_CAR_REQUEST = "GET_CAR_REQUEST";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const GET_CAR_ERROR = "GET_CAR_ERROR";

export const GET_ALLCAR_REQUEST = "GET_ALLCAR_REQUEST";
export const GET_ALLCAR_SUCCESS = "GET_ALLCAR_SUCCESS";
export const GET_ALLCAR_ERROR = "GET_ALLCAR_ERROR";

export const GET_STATECITY_REQUEST = "GET_STATECITY_REQUEST";
export const GET_STATECITY_SUCCESS = "GET_STATECITY_SUCCESS";
export const GET_STATECITY_ERROR = "GET_STATECITY_ERROR";