export const GET_LOGIN_REQUEST = 'GET/GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET/GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET/GET_LOGIN_FAILURE';
export const GET_LOGIN_RESET = 'GET/GET_LOGIN_RESET';

export const GET_LOGOUT = 'GET/GET_LOGOUT_SUCCESS';